"""empty message

Revision ID: 781041a10e32
Revises: 7b78f864414b
Create Date: 2026-01-07 23:59:21.354205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '781041a10e32'
down_revision = '7b78f864414b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))
        batch_op.drop_column('is_active')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))
        batch_op.drop_index(batch_op.f('idx_user_role_active'))
        batch_op.create_index('idx_user_role_active', ['role', 'is_verified'], unique=False)
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_index('idx_user_role_active')
        batch_op.create_index(batch_op.f('idx_user_role_active'), ['role', 'is_active'], unique=False)
        batch_op.drop_column('is_verified')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
