"""empty message

Revision ID: e8961e598c85
Revises: 3e1984c90736
Create Date: 2026-01-12 23:36:01.142265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8961e598c85'
down_revision = '3e1984c90736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('EARNED', 'REDEEMED', 'BONUS', 'ADJUSTED', name='pointstransactiontype'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_points_transactions_order_id_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_points_transactions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_points_transactions'))
    )
    with op.batch_alter_table('points_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_points_transactions_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_points_transactions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_earned', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('points_redeemed', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_balance', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('lifetime_points_earned', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lifetime_points_earned')
        batch_op.drop_column('points_balance')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('points_redeemed')
        batch_op.drop_column('points_earned')

    with op.batch_alter_table('points_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_points_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_points_transactions_order_id'))

    op.drop_table('points_transactions')
    # ### end Alembic commands ###
